---
title: "GLM regression -Census data"
author: "Zoe"
date: "5/11/2021"
output: 
  prettydoc::html_pretty:
    theme: architect
    highlight: github

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE, warning = FALSE)

```


### Load libaries
```{r libraries}
library(plm)
library(data.table)
library(DT)
library(rmarkdown)
library(emmeans)
library(finalfit)
library(knitr)
```


### Import data

```{r import data}
# import data 
df = read.csv("weeks.csv")
num.lines <- 100
question.counter <- 0
```

```{r show dt}
dat <- fread("weeks.csv")
datatable(dat,rownames = TRUE)
```


####The distribution of outcome looks pretty normal??

```{r distribution of dv}
library(ggplot2)
ggplot(df, aes(x = Value)) +
    geom_density(alpha = .2, fill = "#FF6666")
```
```{r grouptogether}
fit11 <- glm(Value ~ Subgroup+Week+Group*Week, data=df, family=Gamma(link = 'log'))
summary(fit11)

```



```{r change week to factor}
df$Week<-as.factor(df$Week)
```

```{r subset groups gender}
df_gender = subset(df, Group == 'gender')
df_gender
```

GLM by gender
```{r glm1 gender}
fitgender <- glm(Value ~ Subgroup+Week, data=df_gender, family=Gamma(link = 'log'))
summary(fitgender)

# Compute the analysis of variance
gender.aov <- aov(Value ~ Subgroup+Week, data = df_gender)
# Summary of the analysis
summary(gender.aov)
```

```{r plot1}
emmip(fitgender, Subgroup ~ Week)
gendermeans<- emmeans(fitgender,"Subgroup", type = "response")
pairs(gendermeans, reverse = TRUE)
gendermeans
```

```{r kable, echo = FALSE, results='asis'}
kable(gendermeans)
```

 GLM by Race
```{r subset groups race}
df_race = subset(df, Group == 'race')
df_race
```


```{r glm race}
fitrace <- glm(Value ~ Subgroup+Week, data=df_race, family=Gamma(link = 'log'))
summary(fitrace)
race.aov <- aov(Value ~ Subgroup+Week, data = df_race)
# Summary of the analysis
summary(race.aov)

```



```{r plot2}
emmip(fitrace, Subgroup ~ Week)
```

GLM by education

```{r subset groups education}
df_education = subset(df, Group == 'education')
df_education
```


```{r glm3 educaton}
fiteducation <- glm(Value ~ Subgroup+Week, data=df_education, family=Gamma(link = "log"))

summary(fiteducation)
edu.aov <- aov(Value ~ Subgroup+Week, data = df_education)
# Summary of the analysis
summary(edu.aov)
```


```{r emmean education}
emmip(fiteducation, Subgroup ~ Week)
eduemm<-emmeans(fiteducation,"Subgroup" , type = "response")
kable(eduemm)
```

```{r educationemm, echo = FALSE, results='asis'}
kable(eduemm)
```

GLM by age

```{r subset age groups}
df_age = subset(df, Group == 'age')
```


```{r glm age}
fitage <- glm(Value ~ Subgroup+Week, data=df_age, family=Gamma (link = 'log'))
summary(fitage)
```

```{r emm}
age.emm <- emmeans(fitage, "Subgroup", type = "response")
age.emm 

```


```{r ageem, echo = FALSE, results='asis'}
kable(age.emm)
```


